services:
  - type: web
    name: subscription-page
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your_database_name
          property: connectionString